import { analyzeDmTrace, DM_METRICS } from './dm.mjs';

const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=value=>value===null?'—':Number(value).toFixed(1);
const grade=(value,spec)=>value<spec.poor?'poor':value<spec.good?'watch':'good';
const color={poor:'#df6558',watch:'#e5a346',good:'#17a583'};
const xMap=sample=>sample.x*9, yMap=sample=>sample.y*5.4;

export function dmSampleDetails(sample,spec) {
  if(!sample) return '<div class="dm-empty">No samples for this radio technology. Choose another filter or import a trace containing it.</div>';
  return `<div class="dm-sample-summary"><strong>${sample.technology==='NR'?'5G NR':'4G LTE'}</strong><span>${esc(sample.servingCell)}</span></div><div class="dm-sample-main"><span>Sample #${sample.index+1} · t=${fmt(sample.timeS)} s</span><strong class="dm-value ${grade(sample[spec.key],spec)}">${fmt(sample[spec.key])} ${spec.unit}</strong></div><div class="dm-sample-rows"><div><span>RSRP / SS-RSRP</span><strong>${fmt(sample.rsrpDbm)} dBm</strong></div><div><span>RSRQ / SS-RSRQ</span><strong>${fmt(sample.rsrqDb)} dB</strong></div><div><span>SINR / SS-SINR</span><strong>${fmt(sample.sinrDb)} dB</strong></div><div><span>DL / UL throughput</span><strong>${fmt(sample.dlMbps)} / ${fmt(sample.ulMbps)} Mbps</strong></div><div><span>Event annotation</span><strong>${esc(sample.event||'none')}</strong></div><div><span>Plot location</span><strong>${fmt(sample.x)}%, ${fmt(sample.y)}%</strong></div></div><p class="dm-caveat">${sample.provenance==='illustrative-not-measured'?'Synthetic demonstration · no radio model produced this point.':'CSV import · source and RF calibration not verified.'}</p>`;
}

function mapChart(p,trace,stats,spec,selected) {
  const all=trace.samples;
  const allStride=Math.max(1,Math.ceil(all.length/350));
  const faded=all.filter((_,i)=>i%allStride===0||i===all.length-1).map(s=>`${xMap(s)},${yMap(s)}`).join(' ');
  const filtered=stats.filtered,stride=Math.max(1,Math.ceil(filtered.length/750));
  const segments=[];
  for(let i=stride;i<filtered.length;i+=stride) {
    const a=filtered[i-stride],b=filtered[i];
    if(b.index-a.index>stride) continue;
    segments.push(`<line x1="${xMap(a)}" y1="${yMap(a)}" x2="${xMap(b)}" y2="${yMap(b)}" stroke="${color[grade(b[spec.key],spec)]}" stroke-width="7" stroke-linecap="round"/>`);
  }
  return `<div class="dm-map"><svg viewBox="0 0 900 540" role="img" aria-label="Schematic drive route colored by ${esc(spec.label)}; not a georeferenced street map"><rect width="900" height="540" fill="#eef6f8"/><path d="M0 460 Q340 410 900 485 L900 540 L0 540Z" fill="#d8edf3"/><g stroke="#bdd4dc" stroke-width="12" fill="none"><path d="M0 120 L900 230"/><path d="M80 400 L900 345"/><path d="M160 0 L265 540"/><path d="M600 0 L445 540"/></g><polyline points="${faded}" fill="none" stroke="#8caeb5" stroke-width="4" stroke-dasharray="8 6"/>${segments.join('')}${p.sites.map(s=>`<g><circle cx="${s.x*9}" cy="${s.y*5.4}" r="10" fill="#fff" stroke="#218a80" stroke-width="3"/><text x="${s.x*9+14}" y="${s.y*5.4-12}" fill="#376273" font-size="12">${esc(s.id)}</text></g>`).join('')}<g id="dm-marker" transform="translate(${selected?xMap(selected):0} ${selected?yMap(selected):0})" ${selected?'':'display="none"'}><circle r="16" fill="#ffffff" stroke="#143e50" stroke-width="4"/><circle r="5" fill="#139b7f"/></g></svg><div class="dm-map-caption">${trace.coordinateMode==='gps-normalized-schematic'?'GPS coordinates normalized to this canvas · NOT aligned with OSM':'Canvas percentages · NOT georeferenced'}</div></div>`;
}
function trendChart(stats,spec,position) {
  const samples=stats.filtered;
  if(!samples.length) return '<div class="dm-empty">No matching samples for the trend chart.</div>';
  const values=samples.map(s=>s[spec.key]);
  const minimum=Math.min(...values,spec.poor)-(spec.unit==='Mbps'?4:5);
  const maximum=Math.max(...values,spec.good)+(spec.unit==='Mbps'?4:5);
  const x=i=>42+850*i/Math.max(1,samples.length-1);
  const y=v=>200-165*(v-minimum)/(maximum-minimum);
  const stride=Math.max(1,Math.ceil(samples.length/500));
  const lines=[];
  for(let i=stride;i<samples.length;i+=stride) {
    const a=samples[i-stride],b=samples[i];
    if(b.index-a.index>stride) continue;
    lines.push(`<line x1="${x(i-stride)}" y1="${y(a[spec.key])}" x2="${x(i)}" y2="${y(b[spec.key])}" stroke="${color[grade(b[spec.key],spec)]}" stroke-width="3" stroke-linecap="round"/>`);
  }
  return `<div class="dm-trend"><svg viewBox="0 0 940 235" role="img" aria-label="${esc(spec.label)} trend by sample number, with illustrative quality thresholds"><g stroke="#e3edf0" stroke-width="1"><line x1="42" y1="35" x2="900" y2="35"/><line x1="42" y1="117" x2="900" y2="117"/><line x1="42" y1="200" x2="900" y2="200"/></g><line x1="42" y1="${y(spec.poor)}" x2="900" y2="${y(spec.poor)}" stroke="#de948b" stroke-width="1.5" stroke-dasharray="6 5"/>${lines.join('')}<line id="dm-trend-cursor" x1="${x(position)}" x2="${x(position)}" y1="30" y2="204" stroke="#153b4e" stroke-width="2" stroke-dasharray="5 5"/><g fill="#577381" font-size="11"><text x="2" y="39">${fmt(maximum)}</text><text x="2" y="${y(spec.poor)-7}">${fmt(spec.poor)}</text><text x="2" y="204">${fmt(minimum)}</text><text x="42" y="224">start</text><text x="857" y="224">end</text></g></svg></div>`;
}
export function dmView(project,h,trace,{technology='ALL',metric='rsrp',position=0,filename='',playing=false}={}) {
  const stats=analyzeDmTrace(trace.samples,{technology,metric}),spec=DM_METRICS[metric];
  const cursor=Math.min(position,Math.max(0,stats.sampleCount-1)),selected=stats.filtered[cursor];
  const sourceDemo=trace.source==='synthetic-demo';
  const sourceBadge=sourceDemo?'SYNTHETIC DEMO · NOT MEASURED':'IMPORTED CSV · UNVERIFIED';
  const toolbar=`<div class="dm-toolbar"><label class="form-field"><span>Radio access</span><select class="select" id="dm-technology"><option value="ALL" ${technology==='ALL'?'selected':''}>4G + 5G</option><option value="LTE" ${technology==='LTE'?'selected':''}>4G LTE</option><option value="NR" ${technology==='NR'?'selected':''}>5G NR</option></select></label><label class="form-field"><span>Color route by</span><select class="select" id="dm-metric">${Object.entries(DM_METRICS).map(([id,m])=>`<option value="${id}" ${id===metric?'selected':''}>${m.label}</option>`).join('')}</select></label><label class="button outline dm-import">↥ Import DM CSV<input type="file" id="dm-csv" accept=".csv,text/csv" hidden/></label><button class="button outline" id="dm-reset">Reset demo</button><button class="button outline" id="dm-export">⇩ Analysis JSON</button></div>`;
  const numbers=`<div class="dm-stats"><article><span>AVERAGE ${esc(spec.label)}</span><strong>${fmt(stats.average)} <small>${spec.unit}</small></strong><em>${stats.sampleCount} selected · LTE ${stats.techCounts.LTE} / NR ${stats.techCounts.NR}</em></article><article><span>10TH PERCENTILE</span><strong>${fmt(stats.p10)} <small>${spec.unit}</small></strong><em>Lower-tail diagnostic · example threshold ${spec.poor} ${spec.unit}</em></article><article><span>WEAK SAMPLES</span><strong>${stats.weakCount} <small>/ ${stats.sampleCount}</small></strong><em>${fmt(stats.weakPercent)}% below example threshold · ${stats.weakZones.length} zones</em></article><article><span>RAN MOBILITY EVENTS</span><strong>${stats.handoverCount} <small>annotated HO</small></strong><em>${stats.cellChangeCount} adjacent serving-cell changes</em></article></div>`;
  const tracePanel=`<div class="dm-legend"><span><i class="dm-dot good"></i> ≥ ${spec.good} ${spec.unit} · strong</span><span><i class="dm-dot watch"></i> ${spec.poor}–${spec.good} · watch</span><span><i class="dm-dot poor"></i> &lt; ${spec.poor} · weak</span><em>Example bands for UI review; tune against a real network acceptance policy.</em></div>${mapChart(project,trace,stats,spec,selected)}<div class="dm-playback"><button id="dm-play" class="button primary" ${!stats.sampleCount?'disabled':''}>${playing?'Ⅱ Pause':'▶ Play trace'}</button><input id="dm-position" type="range" aria-label="DM trace sample" min="0" max="${Math.max(0,stats.sampleCount-1)}" value="${cursor}" ${!stats.sampleCount?'disabled':''}/><strong id="dm-position-label">${stats.sampleCount?cursor+1:0} / ${stats.sampleCount}</strong></div>`;
  const active=`<div id="dm-selected">${dmSampleDetails(selected,spec)}</div>`;
  const events=stats.events.slice(0,20).map(s=>`<button class="dm-event" data-dm-jump="${s.index}"><span>#${s.index+1} · ${fmt(s.timeS)} s</span><strong>${esc(s.event)}</strong><small>${esc(s.technology)} · ${esc(s.servingCell)}</small></button>`).join('');
  const zones=stats.weakZones.slice(0,12).map(z=>`<button class="dm-event dm-weak" data-dm-jump="${z.start}"><span>SAMPLES ${z.start+1}–${z.end+1}</span><strong>${esc(spec.label)} below ${spec.poor} ${spec.unit}</strong><small>Review trace segment →</small></button>`).join('');
  const rows=stats.filtered.slice(Math.max(0,cursor-10),Math.max(0,cursor-10)+25).map(s=>`<tr class="${s.index===selected?.index?'dm-row-selected':''}"><td><button data-dm-jump="${s.index}">#${s.index+1}</button></td><td>${fmt(s.timeS)} s</td><td>${s.technology==='NR'?'5G NR':'4G LTE'}</td><td>${esc(s.servingCell)}</td><td class="${grade(s.rsrpDbm,DM_METRICS.rsrp)}">${fmt(s.rsrpDbm)}</td><td>${fmt(s.rsrqDb)}</td><td class="${grade(s.sinrDb,DM_METRICS.sinr)}">${fmt(s.sinrDb)}</td><td>${fmt(s.dlMbps)}</td><td>${esc(s.event||'—')}</td></tr>`).join('');
  return `<div class="dm-source"><div><strong>${sourceBadge}</strong><span>${sourceDemo?'Deterministic UI illustration derived from the planned route, not Sionna-RT, measured RF, or an executed UE/RAN job.':`Local file ${esc(filename)}; provenance, calibration and network origin have not been verified.`}</span></div><small>ANALYSIS MODE</small></div>${toolbar}${numbers}<div class="dm-main">${h.panel('Drive trace & RF quality','Colored by '+spec.label+' · click timeline events or scrub the cursor',tracePanel,h.badge(sourceDemo?'DEMO TRACE':'IMPORTED TRACE','warn'))}${h.panel('Selected sample','Per-sample LTE/NR DM inspector; all sources disclosed',active,h.badge(selected?.technology==='NR'?'5G NR':selected?'4G LTE':'NO DATA'))}</div>${h.panel('KPI trend / sample sequence','Compare quality over the drive trace; dashed reference is a UI-only threshold',trendChart(stats,spec,cursor),h.badge(`${stats.sampleCount} SAMPLES`))}<div class="lower-grid">${h.panel('Event timeline',`${stats.events.length} event annotations · not all cell changes imply successful handovers`,events?`<div class="dm-event-list">${events}</div>`:'<div class="dm-empty">No handover or RAT events in the selected technology. This is not proof of zero mobility failures.</div>')}${h.panel('Weak-zone review',`${stats.weakZones.length} contiguous segments below example ${spec.label} threshold`,zones?`<div class="dm-event-list">${zones}</div>`:'<div class="dm-empty">No points below the example threshold in this filtered trace. Not a coverage guarantee.</div>')}</div>${h.panel('Sample explorer','Showing a 25-row window around the selected cursor; imported measurements remain unverified',`<div class="table-wrap"><table class="data-table dm-table"><thead><tr><th>POINT</th><th>TIME</th><th>RAT</th><th>SERVING CELL</th><th>RSRP / SS-RSRP</th><th>RSRQ / SS-RSRQ</th><th>SINR / SS-SINR</th><th>DL Mbps</th><th>EVENT</th></tr></thead><tbody>${rows||'<tr><td colspan="9">No samples match this radio filter.</td></tr>'}</tbody></table></div><div class="detail-copy">For a real drive-test verdict, integrate georeferenced trace alignment, run ID, Sionna-RT/channel provenance, RAN package and UE runtime evidence, calibration and acceptance limits. This browser does not infer pass/fail.</div>`,h.badge('NO ACCEPTANCE VERDICT','warn'))}`;
}
