import { topologySummary } from './management.mjs';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const serverId=(pool,slot)=>`${pool.id}-S${String(slot).padStart(2,'0')}`;

function topologyView(m,selected) {
  const pools=m.topology.gh200Pools;
  const ys=[70,160,250,340];
  const paths=`<path d="M255 204 H389"/><path d="M541 204 H615 V70 H666"/><path d="M541 204 H666 V160"/><path d="M541 204 H666 V250"/><path d="M541 204 H615 V340 H666"/>`;
  return `<div class="hw-topology"><svg viewBox="0 0 980 405" role="img" aria-label="Planned Ethernet fronthaul topology: real vDU pool to switch fabric to four GH200 pools; all links unverified"><rect width="980" height="405" fill="#f7fbfc"/><g class="hw-wire">${paths}</g><g class="hw-node hw-vdu"><rect x="33" y="160" width="220" height="88" rx="12"/><text x="49" y="188">REAL NETWORK ELEMENT</text><text class="hw-node-title" x="49" y="213">vDU server pool</text><text x="49" y="234">Physical DU compute · count TBD</text></g><g class="hw-node hw-switch"><rect x="390" y="158" width="152" height="92" rx="12"/><text x="404" y="182">ETHERNET FABRIC</text><text class="hw-node-title" x="404" y="207">Switch</text><text x="404" y="229">Ports TBD · unverified</text></g>${pools.map((pool,i)=>`<g class="hw-node hw-pool ${pool.id===selected.id?'selected':''}" data-pool-select="${pool.id}" role="button" tabindex="0" aria-label="Select ${esc(pool.alias)}"><rect x="667" y="${ys[i]-31}" width="277" height="65" rx="11"/><text x="683" y="${ys[i]-9}">POOL ${String(i+1).padStart(2,'0')}</text><text class="hw-node-title" x="683" y="${ys[i]+11}">${esc(pool.alias)}</text><text x="683" y="${ys[i]+28}">${pool.plannedServers} of 6 GH200 target slots · no discovery</text></g>`).join('')}<text class="hw-link-label" x="270" y="187">Ethernet fronthaul target</text><text class="hw-link-label" x="552" y="393">4 planned pool branches · 0 links verified</text></svg><div class="hw-topology-key"><span>REAL vDU POOL</span><span>ETHERNET SWITCH FABRIC</span><span>GH200 POOLS · VIRTUAL RU / H200 / GRACE TARGETS</span><strong>5 unverified Ethernet links</strong></div></div>`;
}
function rackCabinet(pool,selected,isometric) {
  return `<button type="button" class="hw-rack-button ${pool.id===selected.id?'selected':''}" data-pool-select="${pool.id}" aria-label="Select ${esc(pool.alias)} rack"><div class="hw-rack-3d ${isometric?'isometric':''}"><div class="hw-rack-top"></div><div class="hw-rack-side"><span>GH200</span></div><div class="hw-rack-front"><div class="hw-rack-header"><b>${pool.id}</b><small>GH200 · GPU SERVER</small></div>${Array.from({length:6},(_,i)=>`<div class="rack-slot ${i<pool.plannedServers?'planned':'reserved'}"><i></i><span>${serverId(pool,i+1)}</span><em>${i<pool.plannedServers?'TARGET':'RESERVED'}</em></div>`).join('')}<div class="hw-rack-base">H200 GPU + GRACE CPU</div></div></div><span class="hw-rack-caption">${esc(pool.alias)} · ${pool.plannedServers}/6 target · not discovered</span></button>`;
}
function rackScene(m,selected,isometric) {
  return `<div class="hw-room"><div class="hw-room-rails"><span>PLANNED PHYSICAL RACK LINEUP · ILLUSTRATION, NOT A HARDWARE SCAN</span><span>FRONT / ISOMETRIC VIEW</span></div><div class="hw-room-head"><div class="hw-room-vdu"><span class="hw-room-symbol">▤</span><strong>Real vDU server pool</strong><small>Count TBD · hardware unverified</small></div><div class="hw-room-switch"><span class="hw-room-symbol">⇄</span><strong>Ethernet switch fabric</strong><small>Ports TBD · no cabling verified</small><div class="hw-ports">${Array.from({length:12},()=>'<i></i>').join('')}</div></div></div><div class="hw-rack-grid">${m.topology.gh200Pools.map(pool=>rackCabinet(pool,selected,isometric)).join('')}</div><div class="hw-room-floor">⌁ vDU → Ethernet switch → GH200 pools → virtual RU / antenna or MMU · planned only</div></div>`;
}
function inspector(m,pool) {
  return `<div class="hw-inspector"><div class="hw-inspector-head"><span class="hw-eyebrow">SELECTED GH200 POOL</span><strong>${esc(pool.alias)}</strong><small>${pool.id} · ${pool.plannedServers} of 6 target slots · 0 discovered</small></div><div class="form-grid pad"><label class="form-field"><span>Planning alias</span><input data-pool-alias="${pool.id}" value="${esc(pool.alias)}" maxlength="80"/></label><label class="form-field"><span>Planned GH200 servers (max 6)</span><input type="number" min="0" max="6" data-pool-count="${pool.id}" value="${pool.plannedServers}"/></label></div><div class="hw-slot-list">${Array.from({length:6},(_,i)=>`<div><span>${serverId(pool,i+1)}</span><strong>${i<pool.plannedServers?'PLANNED · NOT DISCOVERED':'RESERVED · NOT DISCOVERED'}</strong></div>`).join('')}</div><div class="detail-copy">Each planned GH200 host represents an H200 GPU and Grace CPU target. Rack slots are schematic; server model, GPU count, cabling and inventory identity require onsite verification.</div></div>`;
}

export function hardwareView(p,h,{selectedPool='GH-POOL-01',isometric=true}={}) {
  const m=p.management,summary=topologySummary(m);
  const selected=m.topology.gh200Pools.find(x=>x.id===selectedPool)||m.topology.gh200Pools[0];
  const summaryHtml=`<div class="ops-summary hw-summary"><div><strong>${summary.plannedGh200Servers} planned GH200</strong><span>maximum 24 · 4 pools × 6 slots</span></div><div><strong>0</strong><span>discovered servers / verified links</span></div><div><strong>vDU + Ethernet</strong><span>physical server pool & switch targets</span></div></div>`;
  const vduCount=m.topology.vduServerCount===null?'':m.topology.vduServerCount;
  const ports=m.topology.switchPortCount===null?'':m.topology.switchPortCount;
  return h.header('H/W inventory','Review the real vDU pool, interconnecting Ethernet fabric and up to 24 planned GH200 GPU servers.') + h.banner() + `<div class="ops-notice">Physical equipment shown below is a target rack visualization, not live discovery or a 3D scan. The fronthaul paths are logical design links; port wiring, timing and reachability remain unverified.</div>${summaryHtml}`+
    h.panel('Fronthaul topology','Real vDU pool → Ethernet switch → four GH200 pools (six server slots each)',topologyView(m,selected),h.badge('0 / 5 LINKS VERIFIED','warn'))+
    h.panel('Physical rack 3D view','Rotate the planned rack lineup and select any pool to inspect its six GH200 slots',`<div class="hw-rotate"><button id="hw-rotate" class="button outline" aria-pressed="${isometric}">${isometric?'▣ Front view':'◈ Isometric view'}</button><span>Illustrative enclosures only · no serials, floorplan or cable survey</span></div>${rackScene(m,selected,isometric)}`,h.badge('24 MAX · 4 × 6'))+
    `<div class="lower-grid">${h.panel('Pool detail','Capacity is a planning target, not deployed hardware',inspector(m,selected),h.badge('NOT DISCOVERED','warn'))}${h.panel('Physical capacity targets','Leave unknown quantities blank rather than inventing hardware counts',`<div class="form-grid pad"><label class="form-field"><span>vDU server count (TBD allowed)</span><input type="number" min="1" max="64" placeholder="TBD" data-hw-count="vdu" value="${vduCount}"/></label><label class="form-field"><span>Ethernet switch ports (TBD allowed)</span><input type="number" min="1" max="512" placeholder="TBD" data-hw-count="switch" value="${ports}"/></label></div><div class="check-list"><div class="check-item"><span class="check-icon">·</span><span>Confirm physical vDU hosts and switch model/port map</span><small>PENDING</small></div><div class="check-item"><span class="check-icon">·</span><span>Verify Ethernet fronthaul VLAN, timing, path and reachability</span><small>PENDING</small></div><div class="check-item"><span class="check-icon">·</span><span>Discover GH200/H200/Grace inventory per rack slot</span><small>PENDING</small></div></div>`,h.badge('UNVERIFIED','warn'))}</div>`+
    h.panel('Hardware role registry','Editable target aliases; these are not device discovery records',`<div class="ops-hardware-grid">${m.hardware.map(asset=>`<article class="ops-hardware-card"><span class="ops-asset-icon">${asset.id==='ethernet-switch'?'⇄':asset.id==='vdu-pool'?'▤':asset.id==='gpu-h200'?'◈':asset.id==='cpu-grace'?'◎':asset.id==='fronthaul'?'⌁':'▣'}</span><div><small>${asset.id.toUpperCase()}</small><h3>${asset.name}</h3><p>${asset.role}</p></div><label class="form-field"><span>Planning alias</span><input data-hw-alias="${asset.id}" value="${esc(asset.alias)}" maxlength="80"/></label>${h.badge('NOT DISCOVERED','warn')}</article>`).join('')}</div>`,h.badge('TARGETS ONLY'));
}
