import { schedulePlan } from './tasks.mjs';
import { managementSnapshot } from './management.mjs';
export { hardwareView } from './hardware-workspace.mjs';

const categoryLabel={scene:'Scene / RF',ran:'Virtual RAN',integration:'Real RAN interface',drive:'Drive test',ab:'Package A/B',data:'AI-RAN data',custom:'Custom'};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const noExecution='<div class="ops-notice">Planning calendar only · nothing here is dispatched to GH200, Sionna-RT, a network element, or a background scheduler.</div>';
export function tasksView(p,h,runs=[],selectedRun=null,totalRuns=runs.length,hasMore=false) {
  const sorted=schedulePlan(p.tasks);
  const runRows=runs.length?`<div class="ops-run-list">${runs.map(run=>`<button type="button" class="ops-run-row" data-run-select="${esc(run.id)}"><span><strong>Sionna-RT · ${esc(run.status)}</strong><small>${esc(Number.isFinite(Date.parse(run.createdAt))?new Date(run.createdAt).toLocaleString():run.createdAt)} · ${esc(run.id)}</small></span><span>${run.totalPaths===null?'—':`${run.totalPaths} paths`}</span></button>`).join('')}</div>`:'<p class="detail-copy">No Sionna-RT run has been recorded for this project.</p>';
  const detail=selectedRun?`<div class="ops-run-detail"><strong>Run ${esc(selectedRun.id)}</strong><p>Status: ${esc(selectedRun.status)}${selectedRun.result?` · ${esc(selectedRun.result.totalPaths)} paths`:''}</p>${selectedRun.error?`<p>${esc(selectedRun.error)}</p>`:''}<pre>${esc(JSON.stringify({input:selectedRun.input,result:selectedRun.result},null,2))}</pre></div>`:'';
  return h.header('Task board','Plan the work needed to turn the RAN twin mockup into a verified deployment.') + h.banner() + noExecution + `<div class="ops-summary"><div><strong>${p.tasks.length}</strong><span>planned tasks</span></div><div><strong>${p.tasks.filter(t=>t.dependsOn.length).length}</strong><span>with dependencies</span></div><div><strong>0</strong><span>planned tasks executed</span></div><div><strong>${totalRuns}</strong><span>RT runs recorded</span></div></div>` +
  `<div class="lower-grid">${h.panel('Delivery backlog','Tasks remain planned until external evidence exists',`<div class="ops-task-list">${sorted.map(t=>`<div class="ops-task"><div class="ops-task-index">${t.id}</div><div class="ops-task-main"><strong>${esc(t.title)}</strong><small>${categoryLabel[t.category]} · ${t.priority.toUpperCase()} priority</small></div>${h.badge(t.dependsOn.length?`AFTER ${t.dependsOn.join(', ')}`:'NO DEPENDENCY',t.dependsOn.length?'warn':'')}<label class="ops-date-label">Due <input type="date" data-task-date="${t.id}" value="${t.dueDate}" aria-label="Due date for ${t.id}"/></label></div>`).join('')}</div>`,h.badge('DATABASE PLAN'))}${h.panel('Add a planned task','No task worker or executor is connected',`<form id="add-task-form" class="pad form-grid"><label class="form-field"><span>Task title</span><input name="title" required maxlength="120" placeholder="e.g. Validate antenna patterns"/></label><label class="form-field"><span>Due date</span><input name="dueDate" type="date" required/></label><label class="form-field"><span>Priority</span><select class="select" name="priority"><option value="normal">Normal</option><option value="high">High</option><option value="low">Low</option></select></label><label class="form-field"><span>Depends on</span><select class="select" name="dependency"><option value="">None</option>${p.tasks.map(t=>`<option value="${t.id}">${t.id} · ${esc(t.title)}</option>`).join('')}</select></label><button class="button primary">+ Add to plan</button></form><div class="detail-copy">Dates must follow dependencies. Scheduled dates represent planning intent, not a cron job, deployment slot, or execution guarantee.</div>`,h.badge('NO DISPATCH','warn'))}</div>`+
  h.panel('Task run results','Server-recorded Sionna-RT jobs for this project; planned delivery tasks remain unexecuted.',`${runRows}${detail}<div class="pad"><button type="button" class="button outline" data-run-refresh>Refresh run list</button>${hasMore?'<button type="button" class="button outline" data-run-more>Load older runs</button>':''}</div>`,h.badge(`${totalRuns} ${totalRuns===1?'RUN':'RUNS'}`));
}
export function scheduleView(p,h) {
  const rows=schedulePlan(p.tasks);
  return h.header('Schedule','Sequence scene, virtual-RAN, drive-test, A/B and dataset preparation in one dependency-aware timeline.') + h.banner() + noExecution + h.panel('Planned timeline',`${rows.length} dated tasks · change dates here or in the task board`,`<div class="ops-timeline">${rows.map((t,i)=>`<div class="ops-milestone"><div class="ops-line"><span>${String(i+1).padStart(2,'0')}</span></div><div class="ops-milestone-body"><div><small>${t.dueDate} · ${categoryLabel[t.category]}</small><strong>${esc(t.title)}</strong><span>Prerequisites: ${t.blockers.length?t.blockers.join(', '):'none'}</span></div><label class="ops-date-label">Reschedule <input type="date" data-task-date="${t.id}" value="${t.dueDate}" aria-label="Reschedule ${t.id}"/></label>${h.badge('NOT RUN','warn')}</div></div>`).join('')}</div>`,h.badge('PLANNING ONLY')) + `<div class="lower-grid">${h.panel('Dependency policy','Keep evidence and run order explicit',`<div class="detail-copy">A downstream task may not be due before a prerequisite. Importing a manifest cannot mark jobs complete. Actual scheduling would require an authenticated job service, timezone policy, resource reservations, retries, logs, and operator approval.</div>`)}${h.panel('Operational boundary','Clock time is not a result',`<div class="detail-copy">H200/GH200 capacity, vDU availability and external scene assets have not been checked. This calendar neither starts processes nor sends notifications.</div>`)}</div>`;
}

export function softwareView(p,h) {
  const m=p.management;
  return h.header('Software management','Track intended components and package versions without implying installation.') + h.banner() + `<div class="ops-summary"><div><strong>${m.software.length}</strong><span>software targets</span></div><div><strong>0</strong><span>verified installs</span></div><div><strong>0</strong><span>running services</span></div></div>` + h.panel('Software registry','Edit version targets; no deployments or package downloads occur',`<div class="table-wrap"><table class="data-table"><thead><tr><th>COMPONENT</th><th>ROLE</th><th>TARGET VERSION</th><th>INSTALLATION</th></tr></thead><tbody>${m.software.map(sw=>`<tr><td><strong>${sw.name}</strong><small class="ops-row-id">${sw.id}</small></td><td>${sw.layer}</td><td><input class="ops-version" data-sw-version="${sw.id}" value="${esc(sw.targetVersion)}" aria-label="Target version for ${sw.name}" maxlength="40"/></td><td>${h.badge('NOT VERIFIED','warn')}</td></tr>`).join('')}</tbody></table></div><div class="detail-copy">The two RAN package entries are version targets; the paired experiment plan still requires identical scene, traffic, seeds and verified deployment artifacts.</div>`,h.badge('CONFIGURATION ONLY'));
}
export function monitoringView(p,h) {
  const snapshot=managementSnapshot(p.management);
  return h.header('Monitoring','Prepare observability thresholds and signal inventory for the future twin runtime.') + h.banner() + `<div class="ops-summary"><div><strong>0</strong><span>telemetry samples</span></div><div><strong>4</strong><span>planned signals</span></div><div><strong>OFFLINE</strong><span>collector connection</span></div></div>` + h.panel('Signal status','No hardware, RF, or protocol telemetry is flowing',`<div class="ops-signal-grid">${snapshot.signals.map(s=>`<div class="ops-signal"><small>${s.label}</small><strong>—</strong><span>NO DATA · alert at ${s.threshold}${s.unit}</span></div>`).join('')}</div><div class="detail-copy">No chart line is drawn without timestamps and real samples. Monitoring labels are target contracts, not measurements.</div>`,h.badge('NO DATA','warn')) + `<div class="lower-grid">${h.panel('Alert policy','Thresholds only; no collector or notifications connected',`<div class="form-grid pad">${snapshot.signals.map(s=>`<label class="form-field"><span>${s.label} threshold (${s.unit})</span><input type="number" data-monitor-threshold="${s.id}" value="${s.threshold}" min="1" max="${s.unit==='ms'?'500':'100'}"/></label>`).join('')}</div><div class="detail-copy">Alerts cannot fire until a verified telemetry source, timestamp policy, provenance and alarm router are installed.</div>`)}${h.panel('Future evidence inputs','Separate real health from simulation output',`<div class="check-list">${['GH200 H200/Grace resource metrics','Sionna-RT job status and artifact freshness','Virtual RU / UE process metrics','Real vDU ↔ virtual RU interface metrics','Radio outputs with simulation-run provenance'].map(x=>`<div class="check-item"><span class="check-icon">·</span><span>${x}</span><small>NO SOURCE</small></div>`).join('')}</div>`)}</div>`;
}
