// Shared presentation boundary: the active app and React pilot use the same planning-only template.
/** @type {ReadonlyArray<readonly [string, string, string, 'real' | 'virtual' | 'planned']>} */
export const ARCHITECTURE_BLOCKS = Object.freeze([
  ['vCore','REAL NETWORK ELEMENT','CORE','real'],['vDU','REAL NETWORK ELEMENT','RAN DU','real'],['O-RAN RU','VIRTUAL COMPONENT','RU','virtual'],['Antenna / MMU','VIRTUAL RF FRONT END','RF','virtual'],['Sionna-RT','CHANNEL · PLANNED','RT','planned'],['Software UE','VIRTUAL · GRACE CPU','UE','virtual']
]);
export function renderArchitectureStrip(h) {
  return h.panel('End-to-end twin boundary','Physical network to virtual radio and CPU-based UEs', `<div class="stack-flow">${ARCHITECTURE_BLOCKS.map(([name,kind,icon,mode],i) => `<div class="stack-part"><div class="stack-block ${mode}"><div class="stack-glyph">${icon}</div><strong>${name}</strong><small>${kind}</small></div>${i < ARCHITECTURE_BLOCKS.length - 1 ? '<span class="stack-arrow">→</span>' : ''}</div>`).join('')}</div><div class="stack-foot"><span>PHYSICAL NETWORK SIDE</span><span>VIRTUALIZATION ON GH200 · H200 GPU + GRACE CPU</span></div>`, h.badge('TARGET ARCHITECTURE'));
}

export function renderStackView(project, h) {
  return h.header('Physical-to-virtual RAN stack','Trace what is real, what is virtualized, and where the radio channel model belongs.') + h.banner() + renderArchitectureStrip(h) + `<div class="lower-grid">${h.panel('Real network integration','Configuration metadata; no authentication or live connection', `<div class="form-grid pad">${h.field('vCore endpoint label','integration.vCoreEndpoint',project.integration.vCoreEndpoint,'text','placeholder="Unconfigured"')}${h.field('vDU endpoint label','integration.vDUEndpoint',project.integration.vDUEndpoint,'text','placeholder="Unconfigured"')}</div><div class="detail-copy">Do not enter credentials. This mockup stores labels locally but never contacts these endpoints. The intended handoff is real vCore → real vDU → virtual O-RAN RU.</div>`, h.badge('NOT CONNECTED','warn'))}${h.panel('GH200 compute placement','Target deployment allocation', `<div class="hardware-grid"><div><span>HOST</span><strong>GH200</strong><small>Target superchip platform</small></div><div><span>GPU</span><strong>H200</strong><small>Sionna-RT channel / RF rendering target</small></div><div><span>CPU</span><strong>Grace</strong><small>Software-based virtual UE workload</small></div></div><div class="detail-copy">Hardware discovery, job scheduling, RU execution and UE orchestration are not implemented in the browser prototype.</div>`, h.badge('PLANNED','warn'))}</div>`;
}
