import { expect, test } from '@playwright/test';
import { spawnPython, runToolSync } from '../../scripts/runtime.mjs';
import { createServer } from 'node:net';
import { once } from 'node:events';
import { mkdir, mkdtemp, readFile, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { execFileSync } from 'node:child_process';
import { clickWorkspaceButton } from './navigation';

test('measurement library retains sources and switches working evidence across maps, reload and imports', async ({ page }) => {
  test.setTimeout(90_000);
  const temporary = await mkdtemp(join(tmpdir(), 'atlas-measurement-library-'));
  const socket = createServer(); socket.listen(0, '127.0.0.1'); await once(socket, 'listening');
  const address = socket.address(); if (!address || typeof address === 'string') throw new Error('No port');
  const port = address.port; await new Promise<void>(resolve => socket.close(() => resolve()));
  runToolSync('vite', ['build'], { stdio: 'ignore' });
  const server = spawnPython(['serve.py', '--port', String(port)], { env: { ...process.env, ATLAS_DB_PATH: join(temporary, 'library.sqlite3') }, stdio: 'ignore' });
  try {
    const origin = `http://127.0.0.1:${port}`;
    await expect.poll(async () => { try { return (await page.request.get(`${origin}/api/workspace`)).status(); } catch { return 0; } }).toBe(200);
    const fixture = JSON.parse(execFileSync(process.execPath, ['tests/fixtures/measurement-library.mjs'], { encoding: 'utf8' }));
    expect((await page.request.put(`${origin}/api/workspace`, { data: { revision: 0, workspace: fixture.workspace, artifacts: fixture.artifacts } })).status()).toBe(200);
    const original = fixture.workspace.projects[0].project, records = structuredClone(original.measurementLibrary.records), study = structuredClone(original.study);
    const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
    await page.setViewportSize({ width: 1440, height: 1000 }); await page.goto(`${origin}/?workspace=measurement-datasets`);
    await expect(page.getByRole('heading', { name: 'Measurement datasets', exact: true })).toBeVisible();
    await expect(page.getByLabel('Measurement library context')).toContainText('second.csv');
    await page.getByRole('button', { name: 'Review v1 vendor.csv' }).click();
    const detail = page.getByRole('region', { name: 'Selected measurement dataset' });
    await expect(detail.getByRole('table', { name: 'Retained KPI availability' })).toContainText('2 / 3');
    await expect(detail).toContainText('2 unresolved');
    const downloaded = page.waitForEvent('download'); await detail.getByRole('button', { name: 'Download original CSV' }).click();
    const file = await downloaded, path = await file.path(); expect(path).toBeTruthy();
    expect(await readFile(path!, 'utf8')).toBe(JSON.parse(records[0].inputJson).evidence.rawCsv);
    const directory = 'docs/design-review/measurement-library'; await mkdir(directory, { recursive: true });
    await page.screenshot({ path: `${directory}/library-desktop.png` });
    await page.setViewportSize({ width: 390, height: 844 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
    await detail.scrollIntoViewIfNeeded(); await page.screenshot({ path: `${directory}/library-mobile.png` });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await detail.getByRole('button', { name: 'Use for working analysis' }).click(); await expect(page.getByRole('status')).toContainText('Working dataset selected');
    await detail.getByRole('button', { name: 'Open measurement analysis' }).click();
    await expect(page.locator('#dm-selected .dm-value')).toContainText('-120.0 dBm');
    await clickWorkspaceButton(page, 'City map');
    await expect(page.getByLabel('Selected drive sample')).toContainText('-120.0 dBm');
    await page.getByLabel('Selected drive sample').getByRole('slider').fill('2');
    await expect(page.getByLabel('Selected drive sample')).toContainText('-90.0 dBm');
    await clickWorkspaceButton(page, 'Measurement datasets');
    await page.getByRole('button', { name: 'Review v2 second.csv' }).click();
    await detail.getByRole('button', { name: 'Use for working analysis' }).click(); await expect(page.getByRole('status')).toContainText('Working dataset selected');
    await clickWorkspaceButton(page, 'City map'); await expect(page.getByLabel('Selected drive sample')).toContainText('-100.0 dBm');
    await page.reload(); await expect(page.getByLabel('Selected drive sample')).toContainText('-100.0 dBm');
    await clickWorkspaceButton(page, 'Measurement datasets');
    await page.getByRole('button', { name: 'Clear working selection' }).click(); await expect(page.getByRole('status')).toContainText('Working selection cleared');
    const cleared = await (await page.request.get(`${origin}/api/workspace`)).json();
    expect(cleared.workspace.projects[0].project.driveMeasurements).toBeNull();
    expect(cleared.workspace.projects[0].project.measurementLibrary.records).toEqual(records);
    expect(cleared.workspace.projects[0].project.study).toEqual(study);
    await clickWorkspaceButton(page, 'City map'); await expect(page.getByLabel('Selected drive sample')).toHaveCount(0);
    await clickWorkspaceButton(page, 'Measurement datasets');
    const raw = 'time_s,technology,serving_cell,latitude,longitude,rsrp_dbm\n0,NR,C,37.5,127,-110\n1,NR,C,37.501,127.001,';
    await page.getByLabel('Import measurement CSV').setInputFiles({ name: 'third.csv', mimeType: 'text/csv', buffer: Buffer.from(raw) });
    const review = page.getByRole('region', { name: 'Drive CSV import review' });
    await review.getByRole('button', { name: 'Validate and preview' }).click();
    await review.getByRole('button', { name: 'Save GPS dataset' }).click(); await expect(review).toHaveCount(0);
    await expect(page.getByRole('button', { name: 'Review v3 third.csv' })).toBeVisible();
    await page.reload(); await expect(page.getByLabel('Measurement library context')).toContainText('third.csv');
    const saved = await (await page.request.get(`${origin}/api/workspace`)).json();
    expect(saved.workspace.projects[0].project.measurementLibrary.records.slice(0, 2)).toEqual(records);
    expect(saved.workspace.projects[0].project.study).toEqual(study);
    const forged = structuredClone(saved); forged.workspace.projects[0].project.measurementLibrary.records[0].registeredAt = '2026-10-02T04:00:00Z';
    expect((await page.request.put(`${origin}/api/workspace`, { data: { ...forged, artifacts: fixture.artifacts } })).status()).toBe(400);
    expect((await (await page.request.get(`${origin}/api/workspace`)).json()).revision).toBe(saved.revision);
    const manifest = await page.request.get(`${origin}/api/projects/pilot/artifacts/planning-manifest`);
    expect(manifest.status()).toBe(200);
    expect(errors).toEqual([]);
  } finally {
    if (server.exitCode === null && server.signalCode === null) { const stopped = once(server, 'exit'); server.kill('SIGTERM'); await stopped; }
    await rm(temporary, { recursive: true, force: true });
  }
});
