import { expect, test } from '@playwright/test';
import { readFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { createWorkspaceState } from '../../workspaces.mjs';
import { upgradeProject } from '../../model.mjs';
import { clickWorkspaceButton } from './navigation';

test('reviewed Gangnam evidence is reused across Drive, City and Propagation with durable bookmarks', async ({ page }) => {
  test.setTimeout(60_000);
  const manifest = JSON.parse(await readFile('examples/gangnam-drive-test/gangnam-skt-drive-planning-manifest.json', 'utf8'));
  const csvPath = 'examples/gangnam-drive-test/gangnam-nonhyeon-teheran-synthetic-drive.csv';
  const rawCsv = await readFile(csvPath, 'utf8');
  const project = upgradeProject({ ...manifest, name: manifest.project, useCases: manifest.useCaseConfig, driveMeasurements: null });
  let workspace = createWorkspaceState(project), revision = 1;
  const pageErrors: string[] = [];
  page.on('pageerror', error => pageErrors.push(error.message));
  await page.route('**/api/workspace', async route => {
    if (route.request().method() === 'GET') await route.fulfill({ json: { workspace, revision } });
    else { workspace = route.request().postDataJSON().workspace; await route.fulfill({ json: { revision: ++revision } }); }
  });
  await page.route('**/api/rt/capability', route => route.fulfill({ json: { available: false, platform: 'test', message: 'Local solver is unavailable in this fixture.' } }));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('/');
  await expect(page.getByLabel('Study inventory')).not.toContainText('COVERAGE PROXY');
  await clickWorkspaceButton(page, 'Virtual drive test');
  await page.locator('#dm-csv').setInputFiles(csvPath);
  const review = page.getByRole('region', { name: 'Drive CSV import review' });
  await expect(review).toBeVisible();
  await review.getByLabel('Dataset origin').selectOption('field-measured');
  await review.getByRole('button', { name: 'Validate and preview' }).click();
  await expect(review).toContainText('Origin: synthetic · verification: unverified');
  expect(workspace.projects[0].project.driveMeasurements).toBeNull();
  await review.getByRole('button', { name: 'Save GPS dataset' }).click();
  await expect(review).toHaveCount(0);
  await expect(page.locator('.dm-source')).toContainText('SYNTHETIC DEMO · NOT MEASURED');
  const saved = workspace.projects[0].project.driveMeasurements as unknown as { evidence: { rawCsv: string; sha256: string; origin: string } };
  expect(saved.evidence).toMatchObject({ rawCsv, origin: 'synthetic', sha256: createHash('sha256').update(rawCsv).digest('hex') });
  await page.getByLabel('Color route by').selectOption('sinr');
  await page.getByLabel('Radio access', { exact: true }).selectOption('NR');
  await page.locator('.dm-table button[data-dm-jump="12"]').click();
  await expect(page.locator('#dm-position-label')).toContainText('13 /');
  await clickWorkspaceButton(page, 'City map');
  await expect(page.getByRole('button', { name: 'SINR dB', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByLabel('Drive test technology')).toHaveValue('NR');
  await expect(page.getByLabel('Drive sample position')).toHaveValue('12');
  await clickWorkspaceButton(page, 'Ray tracing lab');
  await expect(page.getByLabel('Drive sample position')).toHaveValue('12');
  await clickWorkspaceButton(page, 'Virtual drive test');
  await expect(page.getByLabel('Color route by')).toHaveValue('sinr');
  await expect(page.locator('#dm-position-label')).toContainText('13 /');
  await expect(page).toHaveURL(/workspace=drive/);
  await page.goBack();
  await expect(page.getByRole('heading', { name: 'Ray-tracing lab' })).toBeVisible();
  await page.goto('/?workspace=drive-analysis');
  await expect(page.getByRole('heading', { name: 'Virtual drive test' })).toBeVisible();
  await expect(page.locator('.dm-source')).toContainText('Local file gangnam-nonhyeon-teheran-synthetic-drive.csv');
  await expect(page.locator('.drive-geographic-map .open-rf-host canvas')).toBeVisible();
  await expect(page.locator('.drive-geographic-map [role="status"]')).toContainText('open map context connected', { timeout: 20_000 });
  const directory = 'docs/design-review/ran-workflow'; await mkdir(directory, { recursive: true });
  await page.screenshot({ path: `${directory}/drive-analysis-desktop.png` });
  await page.locator('.drive-geographic-map').screenshot({ path: `${directory}/drive-geographic-map.png` });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
  await page.screenshot({ path: `${directory}/drive-analysis-mobile.png` });
  expect(pageErrors).toEqual([]);
});
